version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_blog_image:latest  # Custom image name
    container_name: django_blog_app  # Custom container name
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
